drop table IF EXISTS users, items CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE
);

--INSERT INTO users (name, email) VALUES ('updateName', 'updateName@user.com');

--INSERT INTO users (name, email) VALUES ('user', 'user@user.com');

--INSERT INTO users (name, email) VALUES ('user', 'user@user.com');

--INSERT INTO users (name, email) VALUES ('user', 'user@user.com');

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner BIGINT NOT NULL REFERENCES users(id),
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  available BOOLEAN
);